[v1]
"bacon 2.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bandwhich 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"dotter 0.12.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["dotter"]
"du-dust 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-delta 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"grex 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hyperfine 1.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"lsd 0.22.0 (git+https://github.com/Peltoche/lsd.git?branch=master#b5ad6d0d85fe87554c506b000413b10066cbc614)" = ["lsd"]
"mcfly 0.6.1 (path+file:///home/lo/mcfly)" = ["mcfly"]
"procs 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"tealdeer 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"zoxide 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
