[helpers]

[default]
depends = []

[default.files]
zshrc = { target = "~/.zshrc", type = "template" }
bat = { target = "~/.config/bat/config", type = "template" }

# dotter = ""
# zprofile = ""
# zshrc = "~/.zshrc"
[default.variables]
